services:
  postgres:
    image: postgres:16-alpine
    # 1. Nạp file .env vào để lấy các giá trị DB_USER, DB_PASSWORD...
    # env_file:
    #   - ./backend/.env # Không cần thiết nếu dùng environment trực tiếp bên dưới
    environment:
      # 2. Ánh xạ (Map) trực tiếp: Gán giá trị của DB_USER vào POSTGRES_USER
      # Lúc này Docker sẽ lấy giá trị thực từ file .env đổ vào đây
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - voz_pg_data:/var/lib/postgresql/data
    healthcheck:
      # pg_isready chỉ cần chạy là đủ, không nhất thiết phải truyền user phức tạp
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - voz_redis_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'

  nestjs_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - voz_backend_node_modules:/app/node_modules
    env_file:
      - .env #file .env nằm trên root, không phải ở backend nữa
    environment:
      # Ghi đè DB_HOST vì trong Docker, NestJS phải gọi qua tên service 'postgres'
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: http://localhost:3001
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM: noreply@vozclone.local
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_started
      mailhog:
        condition: service_started

  nestjs_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run start:worker:dev
    volumes:
      - ./backend:/app
      - voz_backend_node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: http://localhost:3001
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM: noreply@vozclone.local
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      mailhog:
        condition: service_started

volumes:
  voz_pg_data:
  voz_redis_data:
  voz_backend_node_modules: